name: Container
on:
  push:
    branches:
      - main
    paths:
      - "code/container/**"

  pull_request:
    branches:
      - main
    paths:
      - "code/container/**"

  schedule:
    - cron: '0 0 * * *'

jobs:
  build_and_publish:
    uses: ./.github/workflows/_containerTemplate.yml
    name: "Build & Publish"
    with:
      environment: "dev"
      working_directory: "./code/container"
      registry_uri: "ghcr.io"
      image_namespace_name: "PerfectThymeTech"
      image_name: "GitHubAgentAzure"
    secrets:
      USER_NAME: ${{ github.actor }}
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
